version: "3.9"

# Définition des services pour l'API
services:
  app:
    # Configuration de la construction de l'image
    build:
      context: .  # Chemin du contexte de construction (répertoire courant)
      args:     # creation d'un argument appeler dev avec pour valeur true
        - DEV=true
    
    # Configuration des ports
    ports:
      - "8000:8000"  # Mapping du port du conteneur sur le port de l'hôte
    
    # Configuration des volumes
    volumes:
      - ./app:/app  # Montage du dossier local './app' dans le dossier '/app' du conteneur
    
    # Commande à exécuter lors du démarrage du conteneur
    # Correction de la commande avec le nom correct 'manage.py'
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      
    depends_on:
      - db 
  
  # creation du service de base de donnee
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES=devdb # nom de la bd
      - POSTGRES_USER=devuser # name user of database
      - POSTGRES_PASSWORD=changeme # # password for user of database

volumes:
  dev-db-data:
